### ISSUE TITLE
libmysql.lib이 안열려서요

### ISSUE THREAD

**Issue by SooLeehihi** [SRin23/mart-system#3]
혹시 버전을 낮추거나 링킹이 안되는 것 같아서 그런데 해결방법이 있을까요?

**Comment by SRin23** [comment]
현재 프로젝트 폴더안의 libmysql파일은 ignore file로 삭제하였습니다.
혹시 프로젝트 폴더안의 libmysql파일을 다운받아 사용하셨다면 파일을 삭제하신 후, 해당 컴퓨터에 MySQL을 다운받아 Wiki의 [Mysql과 C 연동하기] 페이지를 참고하여 Database 초기설정을 완료해 주세요. 
(현재 저는 MySQL 8.0 버전을 사용하고 있습니다.)

**Comment by SooLeehihi** [comment]
감사합니다!!
