### ISSUE TITLE
안녕하세요 kernel 오류는 혹시 어떻게 해결하면 좋을까요?

### ISSUE THREAD

**Issue by SooLeehihi** [SRin23/mart-system#4]
libmysql 오류를 해결하니깐 kernel오류가 생겼습니다 혹시 이경우에는 어떻게 해결해야 할까요?

**Comment by SRin23** [comment]
말씀하신것 만으로는 어떤 오류인지 정확히 인지하는 것이 쉽지 않아, 해결 방법으로 적당할진 모르겠으나, Kernel32.dll파일이 누락되어 생긴 오류라면, 수동으로 Kernel32.dll파일을 다운받아 해결할 수 있다고 알고 있습니다.
